### ISSUE TITLE
[BUG] Quick start instructions are broken

### ISSUE THREAD

**Issue by nocnokneo** [tobybatch/kimai2#102]
When running the quick start steps I get:

```
~ $ docker exec kimai2 /opt/kimai/bin/console kimai:reset-dev

                                             
  Command "kimai:reset-dev" is not defined.  
                                             
  Did you mean one of these?                 
      kimai:create-user                      
      kimai:import-v1                        
      kimai:import:customer                  
      kimai:import:timesheet                 
      kimai:install                          
      kimai:plugins                          
      kimai:reload                           
      kimai:update                           
      kimai:version        

~ $ docker exec kimai2 /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN admin

 [ERROR] plainPassword (admin)                                                  
             This value is too short. It should have 8 characters or more.      
                  
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Docker version: `19.03.6, build 369ce74a3c`

**Command used to run the container**
 - `docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-master-prod`

**Comment by kevinpapst** [comment]
Prod images do not contain dev commands, try 
```docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-master-dev```

The password message is hopefully clear.
PRs to fix the docs are appreciated!

**Comment by tobybatch** [comment]
Fixed in #106

**Comment by nocnokneo** [comment]
I still get `Command "kimai:reset-dev" is not defined.`

Changing the password is also failing, but I presume that is because `reset-dev` failed:

<details>
<pre>
$ docker exec kimai2 /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN changemeplease
18:14:30 ERROR     [console] Error thrown while running command "kimai:create-user admin 'admin@example.com' ROLE_SUPER_ADMIN changemeplease". Message: "An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17, t0.auth AS auth_18 FROM kimai2_users t0 WHERE t0.username_canonical = ?' with params ["admin"]:\n\nSQLSTATE[HY000]: General error: 1 no such table: kimai2_users" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "kimai:create-user admin 'admin@example.com' ROLE_SUPER_ADMIN changemeplease","message" => """  An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17, t0.auth AS auth_18 FROM kimai2_users t0 WHERE t0.username_canonical = ?' with params ["admin"]:\n  \n  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users  """]

In AbstractSQLiteDriver.php line 43:
                                                                               
  An exception occurred while executing 'SELECT t0.username AS username_1, t0  
  .username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_  
  canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6,  
   t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_  
  token AS confirmation_token_9, t0.password_requested_at AS password_request  
  ed_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.re  
  gistration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS  
   avatar_16, t0.api_token AS api_token_17, t0.auth AS auth_18 FROM kimai2_us  
  ers t0 WHERE t0.username_canonical = ?' with params ["admin"]:               
                                                                               
  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users                
                                                                               

In PDOConnection.php line 63:
                                                                 
  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users  
                                                                 

In PDOConnection.php line 61:
                                                                 
  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users  
                                                                 

kimai:create-user [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <username> <email> [<role> [<password>]]
</pre>
</details>

**Comment by chiptemm** [comment]
The QuickStart currently says:
> docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-1.8-dev
docker exec kimai2 rm /opt/kimai/var/data/kimai.sqlite
docker exec kimai2 /opt/kimai/bin/console kimai:reset-dev
docker exec kimai2 /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN changemeplease

The process fails at command
`docker exec kimai2 /opt/kimai/bin/console kimai:reset-dev`
returns:
` Command "kimai:reset-dev" is not defined.`

Substitution of the command
`docker exec kimai2 /opt/kimai/bin/console kimai:install`
Succeeds
This can be followed successfully by the subsequent command:
`docker exec kimai2 /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN changemeplease`

Couldn't find reference to `reset-dev` in the repo so hesitant to post a PR to fix the README

**Comment by kevinpapst** [comment]
Can you try to use `docker exec kimai2 APP_ENV=dev /opt/kimai/bin/console kimai:reset-dev`?

Not sure how the dev images are built, maybe there is accidentally prod set as environment.
In prod that command is not available.

Don't know if there is a better way to set environment variables.
I assume that there is a .env file in the box, which says APP_ENV=prod.

**Comment by nocnokneo** [comment]
> Can you try to use docker exec kimai2 APP_ENV=dev /opt/kimai/bin/console kimai:reset-dev?

Required a slightly modified form which gets closer but then reports out of memory errors:

<details>
<summary><pre>$ docker exec -e APP_ENV=dev kimai2 /opt/kimai/bin/console kimai:reset-dev</pre></summary>
<pre>
Created database /opt/kimai/var/data/kimai.sqlite for connection named default

 Dropping database schema...

 [OK] Database schema dropped successfully!                                     


 ! [CAUTION] This operation should not be executed in a production environment! 

 Creating database schema...

 [OK] Database schema created successfully!                                     


   > purging database
   > loading App\DataFixtures\CustomerFixtures
   > loading App\DataFixtures\InvoiceFixtures
   > loading App\DataFixtures\TagFixtures
   > loading App\DataFixtures\UserFixtures
   > loading App\DataFixtures\TeamFixtures
   > loading App\DataFixtures\TimesheetFixtures

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/kimai/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2879

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/error-handler/Error/OutOfMemoryError.php on line 1
</pre>
</details>

**Comment by kevinpapst** [comment]
See https://github.com/tobybatch/kimai2/pull/108

**Comment by flowl** [comment]
The quickstart instructions login do not work, build success, but can't login.

**Comment by tobybatch** [comment]
@flowl I need more info.  Which account can't log in?  Are you using ```kimai:reset-dev``` or is it vanilla after build?  Have you set the ```ADMINMAIL``` and the ```ADMINPASS``` environment vaues?

**Comment by flowl** [comment]
@tobybatch 

I run this like described in the readme, I can navigate http://localhost:8001 but it says invalid credentials:

> If you run the lines below you can hit kimai at http://localhost:8001 and log in with admin / changemeplease The test users listed in the develop section also exist.

```
docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-1.8-dev
docker exec kimai2 rm /opt/kimai/var/data/kimai.sqlite
docker exec kimai2 /opt/kimai/bin/console kimai:reset-dev
docker exec kimai2 /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN changemeplease
```

**Comment by tobybatch** [comment]
OK, when you run kimai:reset-dev it replaces the existing DB with a set of features, when you ran it is prompted you to drop the current DB and re-install the schema.  You can log in with the details here:

https://www.kimai.org/documentation/developers.html

**Comment by flowl** [comment]
So the 4th line (`kimai:create-user`) does not work?

Either of these lines are not working as I can't login with `admin`.

**Comment by tobybatch** [comment]
That should work, what console output do you get when you run it?

**Comment by kevinpapst** [comment]
`kimai:reset-dev` needs the `-n` flag for running in non-interactive mode, otherwise you have to answer questions
Maybe these are skipped and therefor not executed?

**Comment by tobybatch** [comment]
@flowl Can you try with the 1.9 image please:

    docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-1.9-dev

**Comment by flowl** [comment]
@tobybatch @kevinpapst I can't login, nor with the users with the kitten password, nor with the 1.9 image.

Do I need to setup anything not mentioned in those 4 lines?

**Comment by tobybatch** [comment]
@flowl I have just run those 4 commands on and ubuntu 20.04 and I could log.

What OS and version of docker are you using?
Please post the output from the ```kimai:create-user``` command.

**Comment by flowl** [comment]
`Docker version 19.03.8, build afacb8b`

OS: `MacOS 10.15.5`

Here the log. Maybe the migrations go into sqlite3 while runtime is on MySQL?

```
daniel@macbook kimai % docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-1.8-dev
docker exec kimai2 rm /opt/kimai/var/data/kimai.sqlite
docker exec kimai2 /opt/kimai/bin/console kimai:reset-dev
docker exec kimai2 /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN 123gg321
1.8
Using non mysql DB
first run - install kimai

Kimai installation running ...
==============================

Created database /opt/kimai/var/data/kimai.sqlite for connection named default

                    Application Migrations


Migrating up to 20200205115244 from 0

  ++ migrating 20180701120000

     -> CREATE TABLE kimai2_users (id INTEGER NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active BOOLEAN NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles CLOB NOT NULL --(DC2Type:array)
        , PRIMARY KEY(id))
     -> CREATE UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 ON kimai2_users (name)
     -> CREATE UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 ON kimai2_users (mail)
     -> CREATE TABLE kimai2_user_preferences (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, name VARCHAR(50) NOT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))
     -> CREATE INDEX IDX_8D08F631A76ED395 ON kimai2_user_preferences (user_id)
     -> CREATE UNIQUE INDEX UNIQ_8D08F631A76ED3955E237E06 ON kimai2_user_preferences (user_id, name)
     -> CREATE TABLE kimai2_customers (id INTEGER NOT NULL, name VARCHAR(150) NOT NULL, number VARCHAR(50) DEFAULT NULL, comment CLOB DEFAULT NULL, visible BOOLEAN NOT NULL, company VARCHAR(255) DEFAULT NULL, contact VARCHAR(255) DEFAULT NULL, address CLOB DEFAULT NULL, country VARCHAR(2) NOT NULL, currency VARCHAR(3) NOT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mobile VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, homepage VARCHAR(255) DEFAULT NULL, timezone VARCHAR(255) NOT NULL, PRIMARY KEY(id))
     -> CREATE TABLE kimai2_projects (id INTEGER NOT NULL, customer_id INTEGER DEFAULT NULL, name VARCHAR(150) NOT NULL, order_number CLOB DEFAULT NULL, comment CLOB DEFAULT NULL, visible BOOLEAN NOT NULL, budget NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))
     -> CREATE INDEX IDX_407F12069395C3F3 ON kimai2_projects (customer_id)
     -> CREATE TABLE kimai2_activities (id INTEGER NOT NULL, project_id INTEGER DEFAULT NULL, name VARCHAR(150) NOT NULL, comment CLOB DEFAULT NULL, visible BOOLEAN NOT NULL, PRIMARY KEY(id))
     -> CREATE INDEX IDX_8811FE1C166D1F9C ON kimai2_activities (project_id)
     -> CREATE TABLE kimai2_timesheet (id INTEGER NOT NULL, user INTEGER DEFAULT NULL, activity_id INTEGER DEFAULT NULL, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, duration INTEGER DEFAULT NULL, description CLOB DEFAULT NULL, rate NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))
     -> CREATE INDEX IDX_4F60C6B18D93D649 ON kimai2_timesheet (user)
     -> CREATE INDEX IDX_4F60C6B181C06096 ON kimai2_timesheet (activity_id)
     -> CREATE TABLE kimai2_invoice_templates (id INTEGER NOT NULL, name VARCHAR(60) NOT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, address CLOB DEFAULT NULL, due_days INTEGER NOT NULL, vat INTEGER DEFAULT NULL, calculator VARCHAR(20) NOT NULL, number_generator VARCHAR(20) NOT NULL, renderer VARCHAR(20) NOT NULL, payment_terms CLOB DEFAULT NULL, PRIMARY KEY(id))
     -> CREATE UNIQUE INDEX UNIQ_1626CFE95E237E06 ON kimai2_invoice_templates (name)

  ++ migrated (took 21.3ms, used 16M memory)

  ++ migrating 20180715160326

---- more migrations ----

 ------------------------

  ++ finished in 861.8ms
  ++ used 18M memory
  ++ 32 migrations executed
  ++ 359 sql queries

 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.



 // Warming up the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.




 [OK] Congratulations! Successfully installed Kimai 2 version 1.8 (stable)


Kimai2 ready
[Wed Jul 15 12:33:37.536655 2020] [mpm_prefork:notice] [pid 25] AH00163: Apache/2.4.38 (Debian) PHP/7.4.4 configured -- resuming normal operations
[Wed Jul 15 12:33:37.536903 2020] [core:notice] [pid 25] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

**Comment by flowl** [comment]
Oh the problem got obvious when I see the log outside of my console now...

1.9 image is working, 1.8 image brings errors:

```
daniel@macbook kimai % docker exec kimai2 rm /opt/kimai/var/data/kimai.sqlite
daniel@macbook kimai % docker exec kimai2 /opt/kimai/bin/console kimai:reset-dev



  Command "kimai:reset-dev" is not defined.

  Did you mean one of these?
      kimai:create-user
      kimai:import-v1
      kimai:import:customer
      kimai:import:timesheet
      kimai:install
      kimai:plugins
      kimai:reload
      kimai:update
      kimai:version


daniel@macbook kimai %
daniel@macbook kimai % docker exec kimai2 /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN 123gg321
11:42:12 ERROR     [console] Error thrown while running command "kimai:create-user admin 'admin@example.com' ROLE_SUPER_ADMIN 123gg321". Message: "An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17, t0.auth AS auth_18 FROM kimai2_users t0 WHERE t0.username_canonical = ?' with params ["admin"]:\n\nSQLSTATE[HY000]: General error: 1 no such table: kimai2_users" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "kimai:create-user admin 'admin@example.com' ROLE_SUPER_ADMIN 123gg321","message" => """  An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17, t0.auth AS auth_18 FROM kimai2_users t0 WHERE t0.username_canonical = ?' with params ["admin"]:\n  \n  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users  """]

In AbstractSQLiteDriver.php line 43:

  An exception occurred while executing 'SELECT t0.username AS username_1, t0
  .username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_
  canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6,
   t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_
  token AS confirmation_token_9, t0.password_requested_at AS password_request
  ed_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.re
  gistration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS
   avatar_16, t0.api_token AS api_token_17, t0.auth AS auth_18 FROM kimai2_us
  ers t0 WHERE t0.username_canonical = ?' with params ["admin"]:

  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users


In PDOConnection.php line 63:

  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users


In PDOConnection.php line 61:

  SQLSTATE[HY000]: General error: 1 no such table: kimai2_users


kimai:create-user [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <username> <email> [<role> [<password>]]
```

**Comment by kevinpapst** [comment]
> 1.9 image is working, 1.8 image brings errors:

Then the issue is solved, right?

**Comment by flowl** [comment]
@kevinpapst yep solved. Thanks for caring and sorry for the confusion!
